pets:
  - name: 'Placeholder'
    permission: 'pet.placeholder'
    description: 'Placeholder pet'
    idle: 10
    walking: 11
  - name: 'Example'
    permission: 'pet.example'
    description: 'Example pet'
    idle: 12
    walking: 13