main: org.applecraft.applepets.Main
name: ApplePets
version: 1.17.1
api-version: 1.17
author: Glutenshy
description: Custom pets with custom models.

commands:
  pets:
    description: 'ApplePets command'
    aliases: [pet]

permissions:
  applepets.*:
    default: op
    children:
      applepets.pets.reload: true
  applepets.reload:
    default: op
    